# ==========================================
# Sentinel Local — Minimal Elasticsearch Config
# Defaults are for local hosting on a
# raspberry PI or smaller local machines
# ==========================================

# Basic cluster setup
cluster.name: sentinel-local
node.name: sentinel-node-1
discovery.type: single-node

# ------------------------------------------
# Networking
# ------------------------------------------
network.host: 0.0.0.0 # Listen on all interfaces (0.0.0.0) 
http.port: 9200
transport.port: 9300

# ------------------------------------------
# Resource & Performance Limits
# ------------------------------------------
index.number_of_shards: 1
index.number_of_replicas: 0

# Reduce refresh rate to save CPU
index.refresh_interval: 30s

# Limit memory footprint
bootstrap.memory_lock: true
indices.memory.index_buffer_size: 10%
indices.queries.cache.size: 5%
thread_pool.write.queue_size: 200

# ------------------------------------------
# Security
# Defaults to disabled for local/offline use
# ------------------------------------------
xpack.security.enabled: false
xpack.security.enrollment.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# ------------------------------------------
# Logging (quiet)
# ------------------------------------------
logger.level: info